name: Micromamba CI

on: [push]

jobs:
  Micromamba_linux:
    name: Micromamba (Ubuntu-22.04)
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - name: install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: nelson

      - name: cmake configure
        run: |
          micromamba activate nelson  
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_INSTALL_LIBDIR=lib
        shell: micromamba-shell {0}

      - name: make
        run: |
          cd build
          micromamba activate nelson  
          cmake --build . -- -j $(nproc)
        shell: micromamba-shell {0}

      - name: make install
        run: |
          cd build
          micromamba activate nelson  
          make install
        shell: micromamba-shell {0}

      - name: Tests
        run: |
          micromamba activate nelson  
          nelson-cli -f $GITHUB_WORKSPACE/tests/tests.m
        shell: micromamba-shell {0}

  Micromamba_macos:
    name: Micromamba (macOS 12)
    runs-on: macos-12
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: nelson

      - name: cmake configure
        run: |
          micromamba activate nelson  
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_INSTALL_LIBDIR=lib
        shell: micromamba-shell {0}

      - name: make
        run: |
          cd build
          micromamba activate nelson  
          cmake --build . -- -j ${{ steps.cpu-cores.outputs.count }}
        shell: micromamba-shell {0}

      - name: make install
        run: |
          cd build
          micromamba activate nelson  
          make install
        shell: micromamba-shell {0}

      - name: Tests
        run: |
          micromamba activate nelson  
          nelson-cli -f $GITHUB_WORKSPACE/tests/tests.m
        shell: micromamba-shell {0}
